#!/bin/bash

echo '================================================'
echo 'Installing Wazuh Agent on CloudPanel Part 1 of 2'
echo '------------------------------------------------'

echo 'Log into your Wazuh manager.'
echo 'Go to Server Management -> Endpoints Summary.'
echo 'Then click the button to Deploy New Agent.'
echo 'Select the Linux option for DEB amd64.'
echo 'Set the Server Address to the IP address of the Wazuh server.'
echo 'Set unique agent name [matching this Droplet name].'
echo 'Then COPY the command to install the Wazuh Agent on this machine...'
echo ''

read -p $'Have you copied that command generated by Wazuh?\n(Y)\n' COPIED
echo ''
echo 'Now run that command, then run init-cloudpanel-wazuh-2.sh ...'
